# SPDX-FileCopyrightText: 2025 BearingPoint GmbH
#
# SPDX-License-Identifier: Apache-2.0

# Enable full logging for local development
# quarkus.log.level = ALL
# quarkus.log.category."org.lfenergy.compas.scl.data".level = ALL

quarkus.flyway.migrate-at-start = true
quarkus.flyway.locations        = classpath:org/lfenergy/compas/scl/data/repository/postgresql/db/migration

compas.scl-data-service.features.soft-delete-enabled = true

quarkus.security.auth.enabled-in-dev-mode=false

quarkus.http.auth.permission.common.paths=/compas-scl-data-service/api/*
quarkus.http.auth.permission.common.policy=permit

quarkus.http.auth.permission.scl.paths=/compas-scl-data-service/scl/*
quarkus.http.auth.permission.scl.policy=permit

# Run with local PostgreSQL database provided by "app/src/test/resources/docker-compose.yml"
# For more details have a look at the [development documentation](doc/development.md).

#quarkus.datasource.devservices.enabled = false
#quarkus.datasource.db-kind             = postgresql
#quarkus.datasource.jdbc.url            = jdbc:postgresql://${POSTGRESQL_HOST:localhost}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DB:compas}
#quarkus.datasource.jdbc.max-size       = 16
#quarkus.datasource.username            = ${POSTGRESQL_USERNAME:postgres}
#quarkus.datasource.password            = ${POSTGRESQL_PASSWORD:postgres}
