<?xml version="1.0" encoding="UTF-8"?>
<!-- SPDX-FileCopyrightText: 2020 RTE FRANCE -->
<!-- -->
<!-- SPDX-License-Identifier: Apache-2.0 -->

<SCL xmlns="http://www.iec.ch/61850/2003/SCL" xmlns:compas="https://www.lfenergy.org/compas/extension/v1"
     version="2007" revision="B" release="4">
    <Private type="compas_scl">
        <compas:SclName>MiniGrid</compas:SclName>
        <compas:SclFileType>CID</compas:SclFileType>
        <compas:Labels>
            <compas:Label>1Label</compas:Label>
            <compas:Label>Label*2</compas:Label>
            <compas:Label>Label-01</compas:Label>
            <compas:Label>Label-02</compas:Label>
            <compas:Label>Label-03</compas:Label>
            <compas:Label>Label-04</compas:Label>
            <compas:Label>Label-05</compas:Label>
            <compas:Label>Label-06</compas:Label>
            <compas:Label>Label-07</compas:Label>
            <compas:Label>Label-08</compas:Label>
            <compas:Label>Label-09</compas:Label>
            <compas:Label>Label-10</compas:Label>
            <compas:Label>Label-11</compas:Label>
            <compas:Label>Label-12</compas:Label>
            <compas:Label>Label-13</compas:Label>
            <compas:Label>Label-14</compas:Label>
            <compas:Label>Label-15</compas:Label>
            <compas:Label>Label-16</compas:Label>
            <compas:Label>Label-17</compas:Label>
            <compas:Label>Label-18</compas:Label>
            <compas:Label>Label-19</compas:Label>
            <compas:Label>Label-20</compas:Label>
            <compas:Label>Label-21</compas:Label>
        </compas:Labels>
    </Private>
    <Header id="f9283708-bf4f-412c-a1d6-f947b9ac3000" version="1.0.0" revision="Revision" toolID="toolID"
            nameStructure="IEDName"/>
</SCL>