<?xml version="1.0" encoding="UTF-8"?>
<!-- SPDX-FileCopyrightText: 2020 RTE FRANCE -->
<!-- -->
<!-- SPDX-License-Identifier: Apache-2.0 -->

<SCL xmlns="http://www.iec.ch/61850/2003/SCL" xmlns:compas="https://www.lfenergy.org/compas/extension/v1"
     version="2007" revision="B" release="4">
    <Private type="compas_scl">
        <compas:SclName>MiniGrid</compas:SclName>
        <compas:SclFileType>CID</compas:SclFileType>
        <compas:Labels>
            <compas:Label>1Label</compas:Label>
            <compas:Label>Label*2</compas:Label>
        </compas:Labels>
    </Private>
    <Header id="f9283708-bf4f-412c-a1d6-f947b9ac3000" version="1.0.0" revision="Revision" toolID="toolID"
            nameStructure="IEDName"/>
</SCL>