# SPDX-FileCopyrightText: 2021 Alliander N.V.
#
# SPDX-License-Identifier: Apache-2.0

name: Docker Hub Deployment

on:
  release:
    types: [released]

jobs:
  push_to_registry:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
      - name: Build and publish Docker Image
        run: ./gradlew clean build -Dquarkus-profile=publishNativeImage
        env:
          GITHUB_USERNAME: "OWNER"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}